# Use lightweight Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app
COPY . /app
# Install required dependencies directly
RUN pip install --no-cache-dir Flask requests

# Copy application code
COPY auth_load_balancer /app

# Expose port 5001 for the load balancer
EXPOSE 5001

# Start the Flask app
CMD ["python", "auth_load_balancer.py"]
