FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Install system dependencies required for PostgreSQL
RUN apt-get update && apt-get install -y \
    libpq-dev gcc python3-dev && \
    rm -rf /var/lib/apt/lists/*

# Copy project files
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir flask gunicorn flask-cors flask-jwt-extended flask-bcrypt flask-sqlalchemy python-dotenv psycopg2-binary redis flask-caching

# Expose the application port
EXPOSE 8000

# Run the Flask application
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "AuthenticationService:app"]
