FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements.txt first to leverage Docker cache
COPY AuthenticationService/requirements.txt /usr/src/app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the Django project files
COPY AuthenticationService /usr/src/app/

# Expose the port that the app will run on
EXPOSE 8000

# Command to run the application using Django's development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
